AlignParameters:
  Enabled: false
Documentation:
  Enabled: false
AllCops:
  Include:
    - config.ru
    - Gemfile
    - Rakefile
  Exclude:
    - bin/**/*
    - db/**/*
LineLength:
  Max: 120
StringLiterals:
  EnforcedStyle: double_quotes
Style/NegatedIf:
  Enabled: false
