language: ruby
bundler_args: --jobs=3 --retry=3 --without production --without staging
dist: trusty
addons:
  postgresql: "9.6"
services:
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database brave_publishers_test;' -U postgres
