amazon_internal_bucket:
  service: S3
  region: <%= ENV['S3_PUBLISHERS_BUCKET_REGION'] %>
  bucket: <%= ENV['S3_PUBLISHERS_BUCKET_NAME'] %>
  upload:
    grant_full_control: <%= ENV["S3_CANONICAL_ID"] %>
    grant_read: <%= ENV["REWARDS_CDN_CANONICAL_ID"] %>


amazon_public_bucket:
  service: S3
  region: <%= ENV['S3_REWARDS_BUCKET_REGION'] %>
  bucket: <%= ENV['S3_REWARDS_BUCKET_NAME'] %>
  upload:
    grant_full_control: <%= ENV["S3_CANONICAL_ID"] %>
    grant_read: <%= ENV["REWARDS_CDN_CANONICAL_ID"] %>
