# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  # Used for PublisherTokenRequester
  api_eyeshade_base_uri: <%= ENV["API_EYESHADE_BASE_URI"] %>
  api_eyeshade_key: <%= ENV["API_EYESHADE_KEY"] %>
  # Used for PublisherUrlNormalizer
  api_ledger_base_uri: <%= ENV["API_LEDGER_BASE_URI"] %>
  attr_encrypted_key: <%= ENV["ATTR_ENCRYPTED_KEY"] %>
  api_key_docusign: <%= ENV["API_KEY_DOCUSIGN"] %>
  docusign_api_account_id: <%= ENV["DOCUSIGN_API_ACCOUNT_ID"] %>
  docusign_api_username: <%= ENV["DOCUSIGN_API_USERNAME"] %>
  docusign_api_password: <%= ENV["DOCUSIGN_API_PASSWORD"] %>
  docusign_api_endpoint: <%= ENV["DOCUSIGN_API_ENDPOINT"] %>
  docusign_api_version: <%= ENV["DOCUSIGN_API_VERSION"] %>
  docusign_integrator_key: <%= ENV["DOCUSIGN_INTEGRATOR_KEY"] %>
  docusign_template_id_irs_w_8ben: <%= ENV["DOCUSIGN_TEMPLATE_ID_IRS_W_8BEN"] %>
  docusign_template_id_irs_w_8ben_e: <%= ENV["DOCUSIGN_TEMPLATE_ID_IRS_W_8BEN_E"] %>
  docusign_template_id_irs_w_9: <%= ENV["DOCUSIGN_TEMPLATE_ID_IRS_W_9"] %>
  proxy_url: <%= ENV["PROXY_URL"] %>
  mailer_sender: <%= ENV["MAILER_SENDER"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  support_email: <%= ENV["SUPPORT_EMAIL"] %>

development:
  <<: *default
  attr_encrypted_key: 499a4c51df667b4edfab40c1f8b813b7ed6ce02096d59f23b5dcb095369375f6
  secret_key_base: dd7b12788a804315fd75f1ff97fae33310b451c39d83d1d015543d25d0ba034c02fd312e83735f0d0aeaaf70131f26e614629e3c40531b949445b4dfacd3bad3

test:
  <<: *default
  attr_encrypted_key: 44c101d4dab61a9aa6f13ebd63ad361ba79567604c6ac8bb68e0874d9cf84f05
  secret_key_base: 2a6a0e458f1a3513655583c806f654e0b2be3dac10be16cad9562c089384cb968f30a9774f7ed247e95d48d51f21d69edeab89b95d140a1007bae21621b284f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
