name: reviewdog
on: [pull_request]
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.draft == false && github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
      - name: Install scanners
        run: |
          python3 -m pip install --ignore-installed semgrep
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -reporter=github-pr-review -runners=semgrep -tee
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ hashFiles('semgrep.log') }}
        with:
          github_token: ${{ secrets.github_token }}
          labels: needs-security-review
      - uses: actions-ecosystem/action-add-assignees@v1
        if: ${{ hashFiles('semgrep.log') }}
        with:
          github_token: ${{ secrets.github_token }}
          assignees: thypon
      - uses: actions-ecosystem/action-slack-notifier@v1
        if: ${{ hashFiles('semgrep.log') }}
        with:
          slack_token: ${{ secrets.HOTSPOTS_SLACK_TOKEN }}
          message: |
            [semgrep] @${{ github.actor }} pushed commits. /cc @thypon
          channel: secops-hotspots
          color: green
          verbose: true